spring.application.name=task-api-app

spring.datasource.url=jdbc:postgresql://localhost:5432/task_api_db
spring.datasource.username=hatanotakihide
spring.datasource.password=ah19841202

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true